<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class OrderSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
                //
                DB::table('customer_order')->insert([
                    [
                    'id'=> '1',
                    'User_Id'=> '1',
                    'O_Name'=> 'Nurul Lydia',
                    'O_Street_1'=> 'No. 12, Jalan 18/22A, Taman Seri Serdang',
                    'O_Postcode'=> '43300',
                    'O_City'=> 'Serdang',
                    'O_State'=> 'Selangor',
                    'O_Email'=> 'lydia@gmail.com',
                    'O_Phone'=> '0104031234',
                    'O_Payment'=> 'Cash',
                    
                    'T_Pax'=> '3',
                    'O_Total_Price'=> '4.50',
                    'O_Type'=> 'booking',
                    'O_Status'=> '1',
                    'Tracking_No'=> rand(1000, 9999),
                    'Remarks'=> 'Call me',
                    'created_at'=> '2024-01-01 05:20:55.000000',
                    'updated_at'=> '2024-01-01 05:20:55.000000',
                ],
               
                [
                    'id'=> '2',
                    'User_Id'=> '12',
                    'O_Name'=> 'Qian Sheng',
                    'O_Street_1'=> 'KM 3, Jalan Kebun',
                    'O_Postcode'=> '43650',
                    'O_City'=> 'Serdang',
                    'O_State'=> 'Kajang',
                    'O_Email'=> 'chonghg89@gmail.com',
                    'O_Phone'=> '014-3456777',
                    'O_Payment'=> 'Cash',
                    
                    'T_Pax'=> '3',
                    'O_Total_Price'=> '5.00',
                    'O_Type'=> 'booking',
                    'O_Status'=> '1',
                    'Tracking_No'=> rand(1000, 9999),
                    'Remarks'=> 'Call me',
                    'created_at'=> '2024-01-02 05:20:55.000000',
                    'updated_at'=> '2024-01-02 05:20:55.000000',
                ],
                [
                    'id'=> '3',
                    'User_Id'=> '3',
                    'O_Name'=> 'Avinesh A/L Veloo',
                    'O_Street_1'=> '13, Taman Dahlia, Taman Universiti',
                    'O_Postcode'=> '40000',
                    'O_City'=> 'Kajang',
                    'O_State'=> 'Selangor',
                    'O_Email'=> 'avi9@gmail.com',
                    'O_Phone'=> '018-3346769',
                    'O_Payment'=> 'Cash',
                   
                    'T_Pax'=> '3',
                    'O_Total_Price'=> '5.00',
                    'O_Type'=> 'dineIn',
                    'O_Status'=> '1',
                    'Tracking_No'=> rand(1000, 9999),
                    'Remarks'=> 'Call me',
                    'created_at'=> '2024-01-03 05:20:55.000000',
                    'updated_at'=> '2024-01-03 05:20:55.000000',
                ],
                // 4
                [
                    'id'=> '4',
                    'User_Id'=> '4',
                    'O_Name'=> 'Muhammad Adli',
                    'O_Street_1'=> 'No. 12, Jalan 18/22A, Taman Seri Serdang',
                    'O_Postcode'=> '43300',
                    'O_City'=> 'Serdang',
                    'O_State'=> 'Selangor',
                    'O_Email'=> 'adli@gmail.com',
                    'O_Phone'=> '0104031234',
                    'O_Payment'=> 'Cash',
                  
                    'T_Pax'=> '3',
                    'O_Total_Price'=> '5.00',
                    'O_Type'=> 'dineIn',
                    'O_Status'=> '1',
                    'Tracking_No'=> rand(1000, 9999),
                    'Remarks'=> 'Call me',
                    'created_at'=> '2024-02-01 03:20:55.000000',
                    'updated_at'=> '2024-02-01 03:20:55.000000',
                ],
               // 5
                [
                    'id'=> '5',
                    'User_Id'=> '2',
                    'O_Name'=> 'Lim Chong Heng',
                    'O_Street_1'=> 'KM 3, Jalan Kebun',
                    'O_Postcode'=> '43650',
                    'O_City'=> 'Serdang',
                    'O_State'=> 'Kajang',
                    'O_Email'=> 'chonghg89@gmail.com',
                    'O_Phone'=> '014-3456777',
                    'O_Payment'=> 'Cash',
                  
                    'T_Pax'=> '3',
                    'O_Total_Price'=> '5.00',
                    'O_Type'=> 'dineIn',
                    'O_Status'=> '1',
                    'Tracking_No'=> rand(1000, 9999),
                    'Remarks'=> 'Call me',
                    'created_at'=> '2024-02-01 04:20:55.000000',
                    'updated_at'=> '2024-02-01 04:20:55.000000',
                ],
                // 6
                [
                    'id'=> '6',
                    'User_Id'=> '7',
                    'O_Name'=> 'Navitha Pariva',
                    'O_Street_1'=> '13, Taman Dahlia, Taman Universiti',
                    'O_Postcode'=> '40000',
                    'O_City'=> 'Kajang',
                    'O_State'=> 'Selangor',
                    'O_Email'=> 'avi9@gmail.com',
                    'O_Phone'=> '018-3346769',
                    'O_Payment'=> 'Cash',
                   
                    'T_Pax'=> '3',
                    'O_Total_Price'=> '5.00',
                    'O_Type'=> 'dineIn',
                    'O_Status'=> '1',
                    'Tracking_No'=> rand(1000, 9999),
                    'Remarks'=> 'Call me',
                    'created_at'=> '2024-02-01 05:20:55.000000',
                    'updated_at'=> '2024-02-01 05:20:55.000000',
                ], 
                 // 7
                 [
                    'id'=> '7',
                    'User_Id'=> '1',
                    'O_Name'=> 'Nurul Lydia',
                    'O_Street_1'=> 'No. 12, Jalan 18/22A, Taman Seri Serdang',
                    'O_Postcode'=> '43300',
                    'O_City'=> 'Serdang',
                    'O_State'=> 'Selangor',
                    'O_Email'=> 'lydia@gmail.com',
                    'O_Phone'=> '0104031234',
                    'O_Payment'=> 'Cash',
                   
                    'T_Pax'=> '3',
                    'O_Total_Price'=> '5.00',
                    'O_Type'=> 'dineIn',
                    'O_Status'=> '1',
                    'Tracking_No'=> rand(1000, 9999),
                    'Remarks'=> 'Call me',
                    'created_at'=> '2024-03-01 05:20:55.000000',
                    'updated_at'=> '2024-03-01 05:20:55.000000',
                ],
               // 8
                [
                    'id'=> '8',
                    'User_Id'=> '7',
                    'O_Name'=> 'Navitha Pariva',
                    'O_Street_1'=> 'KM 3, Jalan Kebun',
                    'O_Postcode'=> '43650',
                    'O_City'=> 'Serdang',
                    'O_State'=> 'Kajang',
                    'O_Email'=> 'chonghg89@gmail.com',
                    'O_Phone'=> '014-3456777',
                    'O_Payment'=> 'Cash',
                   
                    'T_Pax'=> '3',
                    'O_Total_Price'=> '5.00',
                    'O_Type'=> 'dineIn',
                    'O_Status'=> '1',
                    'Tracking_No'=> rand(1000, 9999),
                    'Remarks'=> 'Call me',
                    'created_at'=> '2024-03-02 05:20:55.000000',
                    'updated_at'=> '2024-03-02 05:20:55.000000',
                ],
                // 9
                [
                    'id'=> '9',
                    'User_Id'=> '9',
                    'O_Name'=> 'Olivia Charles',
                    'O_Street_1'=> '13, Taman Dahlia, Taman Universiti',
                    'O_Postcode'=> '40000',
                    'O_City'=> 'Kajang',
                    'O_State'=> 'Selangor',
                    'O_Email'=> 'avi9@gmail.com',
                    'O_Phone'=> '018-3346769',
                    'O_Payment'=> 'Cash',
                   
                    'T_Pax'=> '3',
                    'O_Total_Price'=> '5.00',
                    'O_Type'=> 'dineIn',
                    'O_Status'=> '1',
                    'Tracking_No'=> rand(1000, 9999),
                    'Remarks'=> 'Call me',
                    'created_at'=> '2024-03-03 05:20:55.000000',
                    'updated_at'=> '2024-03-03 05:20:55.000000',
                ], 
                 // 10
                 [
                    'id'=> '10',
                    'User_Id'=> '11',
                    'O_Name'=> 'Chu Hua Charles',
                    'O_Street_1'=> 'No. 12, Jalan 18/22A, Taman Seri Serdang',
                    'O_Postcode'=> '43300',
                    'O_City'=> 'Serdang',
                    'O_State'=> 'Selangor',
                    'O_Email'=> 'lydia@gmail.com',
                    'O_Phone'=> '0104031234',
                    'O_Payment'=> 'Cash',
                 
                    'T_Pax'=> '3',
                    'O_Total_Price'=> '4.00',
                    'O_Type'=> 'dineIn',
                    'O_Status'=> '1',
                    'Tracking_No'=> rand(1000, 9999),
                    'Remarks'=> 'Call me',
                    'created_at'=> '2024-04-01 05:20:55.000000',
                    'updated_at'=> '2024-04-01 05:20:55.000000',
                ],
               // 11
                [
                    'id'=> '11',
                    'User_Id'=> '11',
                    'O_Name'=> 'Chu Hua Charles',
                    'O_Street_1'=> 'KM 3, Jalan Kebun',
                    'O_Postcode'=> '43650',
                    'O_City'=> 'Serdang',
                    'O_State'=> 'Kajang',
                    'O_Email'=> 'chonghg89@gmail.com',
                    'O_Phone'=> '014-3456777',
                    'O_Payment'=> 'Cash',
                   
                    'T_Pax'=> '3',
                    'O_Total_Price'=> '3.00',
                    'O_Type'=> 'dineIn',
                    'O_Status'=> '1',
                    'Tracking_No'=> rand(1000, 9999),
                    'Remarks'=> 'Call me',
                    'created_at'=> '2024-04-02 05:20:55.000000',
                    'updated_at'=> '2024-04-02 05:20:55.000000',
                ],
                // 12
                [
                    'id'=> '12',
                    'User_Id'=> '15',
                    'O_Name'=> 'Prasanth',
                    'O_Street_1'=> '13, Taman Dahlia, Taman Universiti',
                    'O_Postcode'=> '40000',
                    'O_City'=> 'Kajang',
                    'O_State'=> 'Selangor',
                    'O_Email'=> 'avi9@gmail.com',
                    'O_Phone'=> '018-3346769',
                    'O_Payment'=> 'Cash',
                   
                    'T_Pax'=> '3',
                    'O_Total_Price'=> '5.50',
                    'O_Type'=> 'dineIn',
                    'O_Status'=> '1',
                    'Tracking_No'=> rand(1000, 9999),
                    'Remarks'=> 'Call me',
                    'created_at'=> '2024-04-03 05:20:55.000000',
                    'updated_at'=> '2024-04-03 05:20:55.000000',
                ], 
                 // 13
                 [
                    'id'=> '13',
                    'User_Id'=> '9',
                    'O_Name'=> 'Olivia Charles',
                    'O_Street_1'=> 'No. 12, Jalan 18/22A, Taman Seri Serdang',
                    'O_Postcode'=> '43300',
                    'O_City'=> 'Serdang',
                    'O_State'=> 'Selangor',
                    'O_Email'=> 'lydia@gmail.com',
                    'O_Phone'=> '0104031234',
                    'O_Payment'=> 'Cash',
                   
                    'T_Pax'=> '3',
                    'O_Total_Price'=> '7.00',
                    'O_Type'=> 'dineIn',
                    'O_Status'=> '1',
                    'Tracking_No'=> rand(1000, 9999),
                    'Remarks'=> 'Call me',
                    'created_at'=> '2024-05-01 05:20:55.000000',
                    'updated_at'=> '2024-05-01 05:20:55.000000',
                 ],
               // 14
                [
                    'id'=> '14',
                    'User_Id'=> '10',
                    'O_Name'=> 'Emma Justin',
                    'O_Street_1'=> 'KM 3, Jalan Kebun',
                    'O_Postcode'=> '43650',
                    'O_City'=> 'Serdang',
                    'O_State'=> 'Kajang',
                    'O_Email'=> 'chonghg89@gmail.com',
                    'O_Phone'=> '014-3456777',
                    'O_Payment'=> 'Cash',
                   
                    'T_Pax'=> '3',
                    'O_Total_Price'=> '4.50',
                    'O_Type'=> 'dineIn',
                    'O_Status'=> '1',
                    'Tracking_No'=> rand(1000, 9999),
                    'Remarks'=> 'Call me',
                    'created_at'=> '2024-05-02 05:20:55.000000',
                    'updated_at'=> '2024-05-02 05:20:55.000000',
                ],
                // 15
                [
                    'id'=> '15',
                    'User_Id'=> '3',
                    'O_Name'=> 'Avinesh A/L Veloo',
                    'O_Street_1'=> '13, Taman Dahlia, Taman Universiti',
                    'O_Postcode'=> '40000',
                    'O_City'=> 'Kajang',
                    'O_State'=> 'Selangor',
                    'O_Email'=> 'avi9@gmail.com',
                    'O_Phone'=> '018-3346769',
                    'O_Payment'=> 'Cash',
                  
                    'T_Pax'=> '3',
                    'O_Total_Price'=> '6.00',
                    'O_Type'=> 'dineIn',
                    'O_Status'=> '1',
                    'Tracking_No'=> rand(1000, 9999),
                    'Remarks'=> 'Call me',
                    'created_at'=> '2024-05-03 05:20:55.000000',
                    'updated_at'=> '2024-05-03 05:20:55.000000',
                ], 
                 // 16
                 [
                    'id'=> '16',
                    'User_Id'=> '23',
                    'O_Name'=> 'Ahmad Hazim',
                    'O_Street_1'=> 'No. 12, Jalan 18/22A, Taman Seri Serdang',
                    'O_Postcode'=> '43300',
                    'O_City'=> 'Serdang',
                    'O_State'=> 'Selangor',
                    'O_Email'=> 'lydia@gmail.com',
                    'O_Phone'=> '0104031234',
                    'O_Payment'=> 'Cash',
                  
                    'T_Pax'=> '3',
                    'O_Total_Price'=> '6.00',
                    'O_Type'=> 'dineIn',
                    'O_Status'=> '1',
                    'Tracking_No'=> rand(1000, 9999),
                    'Remarks'=> 'Call me',
                    'created_at'=> '2024-06-01 05:20:55.000000',
                    'updated_at'=> '2024-06-01 05:20:55.000000',
                ],
               // 17
                [
                    'id'=> '17',
                    'User_Id'=> '24',
                    'O_Name'=> 'Iman Shakil',
                    'O_Street_1'=> 'KM 3, Jalan Kebun',
                    'O_Postcode'=> '43650',
                    'O_City'=> 'Serdang',
                    'O_State'=> 'Kajang',
                    'O_Email'=> 'chonghg89@gmail.com',
                    'O_Phone'=> '014-3456777',
                    'O_Payment'=> 'Cash',
                  
                    'T_Pax'=> '3',
                    'O_Total_Price'=> '4.50',
                    'O_Type'=> 'dineIn',
                    'O_Status'=> '1',
                    'Tracking_No'=> rand(1000, 9999),
                    'Remarks'=> 'Call me',
                    'created_at'=> '2024-06-02 05:20:55.000000',
                    'updated_at'=> '2024-06-02 05:20:55.000000',
                ],
                // 18
                [
                    'id'=> '18',
                    'User_Id'=> '25',
                    'O_Name'=> 'Shivaansh',
                    'O_Street_1'=> '13, Taman Dahlia, Taman Universiti',
                    'O_Postcode'=> '40000',
                    'O_City'=> 'Kajang',
                    'O_State'=> 'Selangor',
                    'O_Email'=> 'avi9@gmail.com',
                    'O_Phone'=> '018-3346769',
                    'O_Payment'=> 'Cash',
                  
                    'T_Pax'=> '3',
                    'O_Total_Price'=> '5.00',
                    'O_Type'=> 'dineIn',
                    'O_Status'=> '1',
                    'Tracking_No'=> rand(1000, 9999),
                    'Remarks'=> 'Call me',
                    'created_at'=> '2024-06-03 05:20:55.000000',
                    'updated_at'=> '2024-06-03 05:20:55.000000',
                ],
                 // 19
                 [
                    'id'=> '19',
                    'User_Id'=> '23',
                    'O_Name'=> 'Ahmad Hazim',
                    'O_Street_1'=> 'No. 12, Jalan 18/22A, Taman Seri Serdang',
                    'O_Postcode'=> '43300',
                    'O_City'=> 'Serdang',
                    'O_State'=> 'Selangor',
                    'O_Email'=> 'lydia@gmail.com',
                    'O_Phone'=> '0104031234',
                    'O_Payment'=> 'Cash',
                 
                    'T_Pax'=> '3',
                    'O_Total_Price'=> '5.00',
                    'O_Type'=> 'dineIn',
                    'O_Status'=> '1',
                    'Tracking_No'=> rand(1000, 9999),
                    'Remarks'=> 'Call me',
                    'created_at'=> '2024-07-01 05:20:55.000000',
                    'updated_at'=> '2024-07-01 05:20:55.000000',
                ],
               // 20
                [
                    'id'=> '20',
                    'User_Id'=> '26',
                    'O_Name'=> 'Afiq Hamdan',
                    'O_Street_1'=> 'KM 3, Jalan Kebun',
                    'O_Postcode'=> '43650',
                    'O_City'=> 'Serdang',
                    'O_State'=> 'Kajang',
                    'O_Email'=> 'chonghg89@gmail.com',
                    'O_Phone'=> '014-3456777',
                    'O_Payment'=> 'Cash',
                 
                    'T_Pax'=> '3',
                    'O_Total_Price'=> '5.00',
                    'O_Type'=> 'dineIn',
                    'O_Status'=> '1',
                    'Tracking_No'=> rand(1000, 9999),
                    'Remarks'=> 'Call me',
                    'created_at'=> '2024-07-02 05:20:55.000000',
                    'updated_at'=> '2024-07-02 05:20:55.000000',
                ],
                // 21
                [
                    'id'=> '21',
                    'User_Id'=> '19',
                    'O_Name'=> 'Christine',
                    'O_Street_1'=> '13, Taman Dahlia, Taman Universiti',
                    'O_Postcode'=> '40000',
                    'O_City'=> 'Kajang',
                    'O_State'=> 'Selangor',
                    'O_Email'=> 'avi9@gmail.com',
                    'O_Phone'=> '018-3346769',
                    'O_Payment'=> 'Cash',
                  
                    'T_Pax'=> '3',
                    'O_Total_Price'=> '5.00',
                    'O_Type'=> 'dineIn',
                    'O_Status'=> '1',
                    'Tracking_No'=> rand(1000, 9999),
                    'Remarks'=> 'Call me',
                    'created_at'=> '2024-07-03 05:20:55.000000',
                    'updated_at'=> '2024-07-03 05:20:55.000000',
                ],
                 // 22
                 [
                    'id'=> '22',
                    'User_Id'=> '23',
                    'O_Name'=> 'Ahmad Hazim',
                    'O_Street_1'=> 'No. 12, Jalan 18/22A, Taman Seri Serdang',
                    'O_Postcode'=> '43300',
                    'O_City'=> 'Serdang',
                    'O_State'=> 'Selangor',
                    'O_Email'=> 'lydia@gmail.com',
                    'O_Phone'=> '0104031234',
                    'O_Payment'=> 'Cash',
                 
                    'T_Pax'=> '3',
                    'O_Total_Price'=> '5.00',
                    'O_Type'=> 'dineIn',
                    'O_Status'=> '1',
                    'Tracking_No'=> rand(1000, 9999),
                    'Remarks'=> 'Call me',
                    'created_at'=> '2024-08-01 05:20:55.000000',
                    'updated_at'=> '2024-08-01 05:20:55.000000',
                ],
               // 23
                [
                    'id'=> '23',
                    'User_Id'=> '20',
                    'O_Name'=> 'Shree Tanusha',
                    'O_Street_1'=> 'KM 3, Jalan Kebun',
                    'O_Postcode'=> '43650',
                    'O_City'=> 'Serdang',
                    'O_State'=> 'Kajang',
                    'O_Email'=> 'chonghg89@gmail.com',
                    'O_Phone'=> '014-3456777',
                    'O_Payment'=> 'Cash',
                  
                    'T_Pax'=> '3',
                    'O_Total_Price'=> '5.00',
                    'O_Type'=> 'dineIn',
                    'O_Status'=> '1',
                    'Tracking_No'=> rand(1000, 9999),
                    'Remarks'=> 'Call me',
                    'created_at'=> '2024-08-02 05:20:55.000000',
                    'updated_at'=> '2024-08-02 05:20:55.000000',
                ],
                // 24
                [
                    'id'=> '24',
                    'User_Id'=> '30',
                    'O_Name'=> 'Ammar Idham',
                    'O_Street_1'=> '13, Taman Dahlia, Taman Universiti',
                    'O_Postcode'=> '40000',
                    'O_City'=> 'Kajang',
                    'O_State'=> 'Selangor',
                    'O_Email'=> 'avi9@gmail.com',
                    'O_Phone'=> '018-3346769',
                    'O_Payment'=> 'Cash',
                
                    'T_Pax'=> '3',
                    'O_Total_Price'=> '5.00',
                    'O_Type'=> 'dineIn',
                    'O_Status'=> '1',
                    'Tracking_No'=> rand(1000, 9999),
                    'Remarks'=> 'Call me',
                    'created_at'=> '2024-08-03 05:20:55.000000',
                    'updated_at'=> '2024-08-03 05:20:55.000000',
                ],
                 // 25
                 [
                    'id'=> '25',
                    'User_Id'=> '23',
                    'O_Name'=> 'Ahmad Hazim',
                    'O_Street_1'=> 'No. 12, Jalan 18/22A, Taman Seri Serdang',
                    'O_Postcode'=> '43300',
                    'O_City'=> 'Serdang',
                    'O_State'=> 'Selangor',
                    'O_Email'=> 'lydia@gmail.com',
                    'O_Phone'=> '0104031234',
                    'O_Payment'=> 'Cash',
                 
                    'T_Pax'=> '3',
                    'O_Total_Price'=> '4.00',
                    'O_Type'=> 'dineIn',
                    'O_Status'=> '1',
                    'Tracking_No'=> rand(1000, 9999),
                    'Remarks'=> 'Call me',
                    'created_at'=> '2024-09-01 05:20:55.000000',
                    'updated_at'=> '2024-09-01 05:20:55.000000',
                ],
               // 26
                [
                    'id'=> '26',
                    'User_Id'=> '29',
                    'O_Name'=> 'Adam Ismail',
                    'O_Street_1'=> 'KM 3, Jalan Kebun',
                    'O_Postcode'=> '43650',
                    'O_City'=> 'Serdang',
                    'O_State'=> 'Kajang',
                    'O_Email'=> 'chonghg89@gmail.com',
                    'O_Phone'=> '014-3456777',
                    'O_Payment'=> 'Cash',
                  
                    'T_Pax'=> '3',
                    'O_Total_Price'=> '3.00',
                    'O_Type'=> 'dineIn',
                    'O_Status'=> '1',
                    'Tracking_No'=> rand(1000, 9999),
                    'Remarks'=> 'Call me',
                    'created_at'=> '2024-09-02 05:20:55.000000',
                    'updated_at'=> '2024-09-02 05:20:55.000000',
                ],
                // 27
                [
                    'id'=> '27',
                    'User_Id'=> '26',
                    'O_Name'=> 'Afiq Hamdan',
                    'O_Street_1'=> '13, Taman Dahlia, Taman Universiti',
                    'O_Postcode'=> '40000',
                    'O_City'=> 'Kajang',
                    'O_State'=> 'Selangor',
                    'O_Email'=> 'avi9@gmail.com',
                    'O_Phone'=> '018-3346769',
                    'O_Payment'=> 'Cash',
                  
                    'T_Pax'=> '3',
                    'O_Total_Price'=> '4.50',
                    'O_Type'=> 'dineIn',
                    'O_Status'=> '1',
                    'Tracking_No'=> rand(1000, 9999),
                    'Remarks'=> 'Call me',
                    'created_at'=> '2024-09-03 05:20:55.000000',
                    'updated_at'=> '2024-09-03 05:20:55.000000',
                ],
                 // 28
                 [
                    'id'=> '28',
                    'User_Id'=> '25',
                    'O_Name'=> 'Shivaansh',
                    'O_Street_1'=> 'No. 12, Jalan 18/22A, Taman Seri Serdang',
                    'O_Postcode'=> '43300',
                    'O_City'=> 'Serdang',
                    'O_State'=> 'Selangor',
                    'O_Email'=> 'lydia@gmail.com',
                    'O_Phone'=> '0104031234',
                    'O_Payment'=> 'Cash',
                 
                    'T_Pax'=> '3',
                    'O_Total_Price'=> '5.00',
                    'O_Type'=> 'dineIn',
                    'O_Status'=> '1',
                    'Tracking_No'=> rand(1000, 9999),
                    'Remarks'=> 'Remove all product',
                    'created_at'=> '2024-10-01 05:20:55.000000',
                    'updated_at'=> '2024-10-01 05:20:55.000000',
                ],
               // 29
                [
                    'id'=> '29',
                    'User_Id'=> '2',
                    'O_Name'=> 'Lim Chong Heng',
                    'O_Street_1'=> 'KM 3, Jalan Kebun',
                    'O_Postcode'=> '43650',
                    'O_City'=> 'Serdang',
                    'O_State'=> 'Kajang',
                    'O_Email'=> 'chonghg89@gmail.com',
                    'O_Phone'=> '014-3456777',
                    'O_Payment'=> 'Cash',
                 
                    'T_Pax'=> '3',
                    'O_Total_Price'=> '5.00',
                    'O_Type'=> 'dineIn',
                    'O_Status'=> '1',
                    'Tracking_No'=> rand(1000, 9999),
                    'Remarks'=> 'Call me',
                    'created_at'=> '2024-10-02 05:20:55.000000',
                    'updated_at'=> '2024-10-02 05:20:55.000000',
                ],
                // 30
                [
                    'id'=> '30',
                    'User_Id'=> '14',
                    'O_Name'=> 'Sean Leng',
                    'O_Street_1'=> '13, Taman Dahlia, Taman Universiti',
                    'O_Postcode'=> '40000',
                    'O_City'=> 'Kajang',
                    'O_State'=> 'Selangor',
                    'O_Email'=> 'avi9@gmail.com',
                    'O_Phone'=> '018-3346769',
                    'O_Payment'=> 'Cash',
                 
                    'T_Pax'=> '3',
                    'O_Total_Price'=> '5.00',
                    'O_Type'=> 'dineIn',
                    'O_Status'=> '1',
                    'Tracking_No'=> rand(1000, 9999),
                    'Remarks'=> 'Call me',
                    'created_at'=> '2024-10-03 05:20:55.000000',
                    'updated_at'=> '2024-10-03 05:20:55.000000',
                ],
                 // 31
                 [
                    'id'=> '31',
                    'User_Id'=> '1',
                    'O_Name'=> 'Nurul Lydia',
                    'O_Street_1'=> 'No. 12, Jalan 18/22A, Taman Seri Serdang',
                    'O_Postcode'=> '43300',
                    'O_City'=> 'Serdang',
                    'O_State'=> 'Selangor',
                    'O_Email'=> 'lydia@gmail.com',
                    'O_Phone'=> '0104031234',
                    'O_Payment'=> 'Cash',
                 
                    'T_Pax'=> '3',
                    'O_Total_Price'=> '5.00',
                    'O_Type'=> 'dineIn',
                    'O_Status'=> '1',
                    'Tracking_No'=> rand(1000, 9999),
                    'Remarks'=> 'Call me',
                    'created_at'=> '2024-11-01 05:20:55.000000',
                    'updated_at'=> '2024-11-01 05:20:55.000000',
                ],
               // 32
                [
                    'id'=> '32',
                    'User_Id'=> '9',
                    'O_Name'=> 'Olivia Charles',
                    'O_Street_1'=> 'KM 3, Jalan Kebun',
                    'O_Postcode'=> '43650',
                    'O_City'=> 'Serdang',
                    'O_State'=> 'Kajang',
                    'O_Email'=> 'chonghg89@gmail.com',
                    'O_Phone'=> '014-3456777',
                    'O_Payment'=> 'Cash',
                 
                    'T_Pax'=> '3',
                    'O_Total_Price'=> '5.00',
                    'O_Type'=> 'dineIn',
                    'O_Status'=> '1',
                    'Tracking_No'=> rand(1000, 9999),
                    'Remarks'=> 'Call me',
                    'created_at'=> '2024-11-02 05:20:55.000000',
                    'updated_at'=> '2024-11-02 05:20:55.000000',
                ],
                // 33
                [
                    'id'=> '33',
                    'User_Id'=> '4',
                    'O_Name'=> 'Muhammad Adli',
                    'O_Street_1'=> '13, Taman Dahlia, Taman Universiti',
                    'O_Postcode'=> '40000',
                    'O_City'=> 'Kajang',
                    'O_State'=> 'Selangor',
                    'O_Email'=> 'avi9@gmail.com',
                    'O_Phone'=> '018-3346769',
                    'O_Payment'=> 'Cash',
                 
                    'T_Pax'=> '3',
                    'O_Total_Price'=> '5.00',
                    'O_Type'=> 'dineIn',
                    'O_Status'=> '1',
                    'Tracking_No'=> rand(1000, 9999),
                    'Remarks'=> 'Call me',
                    'created_at'=> '2024-11-03 05:20:55.000000',
                    'updated_at'=> '2024-11-03 05:20:55.000000',
                ],
                 // 34
                 [
                    'id'=> '34',
                    'User_Id'=> '12',
                    'O_Name'=> 'Qian Sheng',
                    'O_Street_1'=> 'No. 12, Jalan 18/22A, Taman Seri Serdang',
                    'O_Postcode'=> '43300',
                    'O_City'=> 'Serdang',
                    'O_State'=> 'Selangor',
                    'O_Email'=> 'lydia@gmail.com',
                    'O_Phone'=> '0104031234',
                    'O_Payment'=> 'Cash',
                  
                    'T_Pax'=> '3',
                    'O_Total_Price'=> '5.00',
                    'O_Type'=> 'dineIn',
                    'O_Status'=> '1',
                    'Tracking_No'=> rand(1000, 9999),
                    'Remarks'=> 'Call me',
                    'created_at'=> '2024-12-01 05:20:55.000000',
                    'updated_at'=> '2024-12-01 05:20:55.000000',
                ],
               // 35
                [
                    'id'=> '35',
                    'User_Id'=> '13',
                    'O_Name'=> 'Dong Si Cheng',
                    'O_Street_1'=> 'KM 3, Jalan Kebun',
                    'O_Postcode'=> '43650',
                    'O_City'=> 'Serdang',
                    'O_State'=> 'Kajang',
                    'O_Email'=> 'chonghg89@gmail.com',
                    'O_Phone'=> '014-3456777',
                    'O_Payment'=> 'Cash',
                 
                    'T_Pax'=> '3',
                    'O_Total_Price'=> '4.00',
                    'O_Type'=> 'dineIn',
                    'O_Status'=> '1',
                    'Tracking_No'=> rand(1000, 9999),
                    'Remarks'=> 'Call me',
                    'created_at'=> '2024-12-02 05:20:55.000000',
                    'updated_at'=> '2024-12-02 05:20:55.000000',
                ],
                // 36
                [
                    'id'=> '36',
                    'User_Id'=> '14',
                    'O_Name'=> 'Sean Leng',
                    'O_Street_1'=> '13, Taman Dahlia, Taman Universiti',
                    'O_Postcode'=> '40000',
                    'O_City'=> 'Kajang',
                    'O_State'=> 'Selangor',
                    'O_Email'=> 'avi9@gmail.com',
                    'O_Phone'=> '018-3346769',
                    'O_Payment'=> 'Cash',
                 
                    'T_Pax'=> '3',
                    'O_Total_Price'=> '3.00',
                    'O_Type'=> 'dineIn',
                    'O_Status'=> '1',
                    'Tracking_No'=> rand(1000, 9999),
                    'Remarks'=> 'Call me',
                    'created_at'=> '2024-12-03 05:20:55.000000',
                    'updated_at'=> '2024-12-03 05:20:55.000000',
                ],
                 // 37
                 [
                    'id'=> '37',
                    'User_Id'=> '17',
                    'O_Name'=> 'Christine',
                    'O_Street_1'=> 'No. 12, Jalan 18/22A, Taman Seri Serdang',
                    'O_Postcode'=> '43300',
                    'O_City'=> 'Serdang',
                    'O_State'=> 'Selangor',
                    'O_Email'=> 'lydia@gmail.com',
                    'O_Phone'=> '0104031234',
                    'O_Payment'=> 'Cash',
                
                    'T_Pax'=> '3',
                    'O_Total_Price'=> '4.50',
                    'O_Type'=> 'booking',
                    'O_Status'=> '1',
                    'Tracking_No'=> rand(1000, 9999),
                    'Remarks'=> 'Call me',
                    'created_at'=> '2024-12-04 05:20:55.000000',
                    'updated_at'=> '2024-12-04 05:20:55.000000',
                ],
               // 38
                [
                    'id'=> '38',
                    'User_Id'=> '9',
                    'O_Name'=> 'Olivia Charles',
                    'O_Street_1'=> 'KM 3, Jalan Kebun',
                    'O_Postcode'=> '43650',
                    'O_City'=> 'Serdang',
                    'O_State'=> 'Kajang',
                    'O_Email'=> 'chonghg89@gmail.com',
                    'O_Phone'=> '014-3456777',
                    'O_Payment'=> 'Cash',
                
                    'T_Pax'=> '3',
                    'O_Total_Price'=> '5.00',
                    'O_Type'=> 'pickUp',
                    'O_Status'=> '1',
                    'Tracking_No'=> rand(1000, 9999),
                    'Remarks'=> 'Call me',
                    'created_at'=> '2024-12-05 05:20:55.000000',
                    'updated_at'=> '2024-12-05 05:20:55.000000',
                ],
                // 39
                [
                    'id'=> '39',
                    'User_Id'=> '3',
                    'O_Name'=> 'Avinesh A/L Veloo',
                    'O_Street_1'=> '13, Taman Dahlia, Taman Universiti',
                    'O_Postcode'=> '40000',
                    'O_City'=> 'Kajang',
                    'O_State'=> 'Selangor',
                    'O_Email'=> 'avi9@gmail.com',
                    'O_Phone'=> '018-3346769',
                    'O_Payment'=> 'Cash',
                 
                    'T_Pax'=> '3',
                    'O_Total_Price'=> '5.00',
                    'O_Type'=> 'delivery',
                    'O_Status'=> '1',
                    'Tracking_No'=> rand(1000, 9999),
                    'Remarks'=> 'Call me',
                    'created_at'=> '2024-02-01 05:20:55.000000',
                    'updated_at'=> '2024-02-01 05:20:55.000000',
                ],
                [
                    'id'=> '40',
                    'User_Id'=> '28',
                    'O_Name'=> 'Haris Ibrahim',
                    'O_Street_1'=> '13, Taman Dahlia, Taman Universiti',
                    'O_Postcode'=> '40000',
                    'O_City'=> 'Kajang',
                    'O_State'=> 'Selangor',
                    'O_Email'=> 'avi9@gmail.com',
                    'O_Phone'=> '018-3346769',
                    'O_Payment'=> 'Cash',
                  
                    'T_Pax'=> '3',
                    'O_Total_Price'=> '5.00',
                    'O_Type'=> 'dineIn',
                    'O_Status'=> '1',
                    'Tracking_No'=> rand(1000, 9999),
                    'Remarks'=> 'Call me',
                    'created_at'=> '2024-07-04 05:20:55.000000',
                    'updated_at'=> '2024-07-04 05:20:55.000000',
                ],
                [
                    'id'=> '41',
                    'User_Id'=> '28',
                    'O_Name'=> 'Haris Ibrahim',
                    'O_Street_1'=> '13, Taman Dahlia, Taman Universiti',
                    'O_Postcode'=> '40000',
                    'O_City'=> 'Kajang',
                    'O_State'=> 'Selangor',
                    'O_Email'=> 'avi9@gmail.com',
                    'O_Phone'=> '018-3346769',
                    'O_Payment'=> 'Cash',
                  
                    'T_Pax'=> '3',
                    'O_Total_Price'=> '5.00',
                    'O_Type'=> 'dineIn',
                    'O_Status'=> '1',
                    'Tracking_No'=> rand(1000, 9999),
                    'Remarks'=> 'Call me',
                    'created_at'=> '2024-08-04 05:20:55.000000',
                    'updated_at'=> '2024-08-04 05:20:55.000000',
                ],
                [
                    'id'=> '42',
                    'User_Id'=> '9',
                    'O_Name'=> 'Olivia Charles',
                    'O_Street_1'=> '13, Taman Dahlia, Taman Universiti',
                    'O_Postcode'=> '40000',
                    'O_City'=> 'Kajang',
                    'O_State'=> 'Selangor',
                    'O_Email'=> 'avi9@gmail.com',
                    'O_Phone'=> '018-3346769',
                    'O_Payment'=> 'Cash',
                 
                    'T_Pax'=> '3',
                    'O_Total_Price'=> '5.00',
                    'O_Type'=> 'dineIn',
                    'O_Status'=> '1',
                    'Tracking_No'=> rand(1000, 9999),
                    'Remarks'=> 'Call me',
                    'created_at'=> '2024-08-05 05:20:55.000000',
                    'updated_at'=> '2024-08-05 05:20:55.000000',
                ],
                [
                    'id'=> '43',
                    'User_Id'=> '11',
                    'O_Name'=> 'Chu Hua Charles',
                    'O_Street_1'=> '13, Taman Dahlia, Taman Universiti',
                    'O_Postcode'=> '40000',
                    'O_City'=> 'Kajang',
                    'O_State'=> 'Selangor',
                    'O_Email'=> 'avi9@gmail.com',
                    'O_Phone'=> '018-3346769',
                    'O_Payment'=> 'Cash',
                 
                    'T_Pax'=> '3',
                    'O_Total_Price'=> '5.00',
                    'O_Type'=> 'dineIn',
                    'O_Status'=> '1',
                    'Tracking_No'=> rand(1000, 9999),
                    'Remarks'=> 'Call me',
                    'created_at'=> '2024-08-06 05:20:55.000000',
                    'updated_at'=> '2024-08-06 05:20:55.000000',
                ],
                [
                    'id'=> '44',
                    'User_Id'=> '12',
                    'O_Name'=> 'Qian Sheng',
                    'O_Street_1'=> '13, Taman Dahlia, Taman Universiti',
                    'O_Postcode'=> '40000',
                    'O_City'=> 'Kajang',
                    'O_State'=> 'Selangor',
                    'O_Email'=> 'avi9@gmail.com',
                    'O_Phone'=> '018-3346769',
                    'O_Payment'=> 'Cash',
                 
                    'T_Pax'=> '3',
                    'O_Total_Price'=> '5.00',
                    'O_Type'=> 'dineIn',
                    'O_Status'=> '1',
                    'Tracking_No'=> rand(1000, 9999),
                    'Remarks'=> 'Call me',
                    'created_at'=> '2024-09-04 05:20:55.000000',
                    'updated_at'=> '2024-09-04 05:20:55.000000',
                ],
                [
                    'id'=> '45',
                    'User_Id'=> '16',
                    'O_Name'=> 'Hakim',
                    'O_Street_1'=> '13, Taman Dahlia, Taman Universiti',
                    'O_Postcode'=> '40000',
                    'O_City'=> 'Kajang',
                    'O_State'=> 'Selangor',
                    'O_Email'=> 'avi9@gmail.com',
                    'O_Phone'=> '018-3346769',
                    'O_Payment'=> 'Cash',
                 
                    'T_Pax'=> '3',
                    'O_Total_Price'=> '5.00',
                    'O_Type'=> 'dineIn',
                    'O_Status'=> '1',
                    'Tracking_No'=> rand(1000, 9999),
                    'Remarks'=> 'Call me',
                    'created_at'=> '2024-09-05 05:20:55.000000',
                    'updated_at'=> '2024-09-05 05:20:55.000000',
                ],
                [
                    'id'=> '46',
                    'User_Id'=> '17',
                    'O_Name'=> 'Christine',
                    'O_Street_1'=> '13, Taman Dahlia, Taman Universiti',
                    'O_Postcode'=> '40000',
                    'O_City'=> 'Kajang',
                    'O_State'=> 'Selangor',
                    'O_Email'=> 'avi9@gmail.com',
                    'O_Phone'=> '018-3346769',
                    'O_Payment'=> 'Cash',
                 
                    'T_Pax'=> '3',
                    'O_Total_Price'=> '5.00',
                    'O_Type'=> 'dineIn',
                    'O_Status'=> '1',
                    'Tracking_No'=> rand(1000, 9999),
                    'Remarks'=> 'Call me',
                    'created_at'=> '2024-10-04 05:20:55.000000',
                    'updated_at'=> '2024-10-04 05:20:55.000000',
                ],
                [
                    'id'=> '47',
                    'User_Id'=> '18',
                    'O_Name'=> 'Shenti',
                    'O_Street_1'=> '13, Taman Dahlia, Taman Universiti',
                    'O_Postcode'=> '40000',
                    'O_City'=> 'Kajang',
                    'O_State'=> 'Selangor',
                    'O_Email'=> 'avi9@gmail.com',
                    'O_Phone'=> '018-3346769',
                    'O_Payment'=> 'Cash',
                 
                    'T_Pax'=> '3',
                    'O_Total_Price'=> '5.00',
                    'O_Type'=> 'dineIn',
                    'O_Status'=> '1',
                    'Tracking_No'=> rand(1000, 9999),
                    'Remarks'=> 'Call me',
                    'created_at'=> '2024-11-04 05:20:55.000000',
                    'updated_at'=> '2024-11-04 05:20:55.000000',
                ],
                [
                    'id'=> '48',
                    'User_Id'=> '21',
                    'O_Name'=> 'Imran',
                    'O_Street_1'=> '13, Taman Dahlia, Taman Universiti',
                    'O_Postcode'=> '40000',
                    'O_City'=> 'Kajang',
                    'O_State'=> 'Selangor',
                    'O_Email'=> 'avi9@gmail.com',
                    'O_Phone'=> '018-3346769',
                    'O_Payment'=> 'Cash',
                 
                    'T_Pax'=> '3',
                    'O_Total_Price'=> '5.00',
                    'O_Type'=> 'dineIn',
                    'O_Status'=> '1',
                    'Tracking_No'=> rand(1000, 9999),
                    'Remarks'=> 'Call me',
                    'created_at'=> '2024-11-05 05:20:55.000000',
                    'updated_at'=> '2024-11-05 05:20:55.000000',
                ],
                [
                    'id'=> '49',
                    'User_Id'=> '23',
                    'O_Name'=> 'Ahmad Hazim',
                    'O_Street_1'=> '13, Taman Dahlia, Taman Universiti',
                    'O_Postcode'=> '40000',
                    'O_City'=> 'Kajang',
                    'O_State'=> 'Selangor',
                    'O_Email'=> 'avi9@gmail.com',
                    'O_Phone'=> '018-3346769',
                    'O_Payment'=> 'Cash',
                 
                    'T_Pax'=> '3',
                    'O_Total_Price'=> '5.00',
                    'O_Type'=> 'dineIn',
                    'O_Status'=> '1',
                    'Tracking_No'=> rand(1000, 9999),
                    'Remarks'=> 'Call me',
                    'created_at'=> '2024-11-06 05:20:55.000000',
                    'updated_at'=> '2024-11-06 05:20:55.000000',
                ],
                [
                    'id'=> '56',
                    'User_Id'=> '25',
                    'O_Name'=> 'Shivaansh',
                    'O_Street_1'=> '13, Taman Dahlia, Taman Universiti',
                    'O_Postcode'=> '40000',
                    'O_City'=> 'Kajang',
                    'O_State'=> 'Selangor',
                    'O_Email'=> 'avi9@gmail.com',
                    'O_Phone'=> '018-3346769',
                    'O_Payment'=> 'Cash',
                 
                    'T_Pax'=> '3',
                    'O_Total_Price'=> '5.00',
                    'O_Type'=> 'dineIn',
                    'O_Status'=> '1',
                    'Tracking_No'=> rand(1000, 9999),
                    'Remarks'=> 'Call me',
                    'created_at'=> '2024-11-07 05:20:55.000000',
                    'updated_at'=> '2024-11-07 05:20:55.000000',
                ],
                [
                    'id'=> '50',
                    'User_Id'=> '25',
                    'O_Name'=> 'Shivaansh',
                    'O_Street_1'=> '13, Taman Dahlia, Taman Universiti',
                    'O_Postcode'=> '40000',
                    'O_City'=> 'Kajang',
                    'O_State'=> 'Selangor',
                    'O_Email'=> 'avi9@gmail.com',
                    'O_Phone'=> '018-3346769',
                    'O_Payment'=> 'Cash',
                 
                    'T_Pax'=> '3',
                    'O_Total_Price'=> '5.00',
                    'O_Type'=> 'dineIn',
                    'O_Status'=> '1',
                    'Tracking_No'=> rand(1000, 9999),
                    'Remarks'=> 'Call me',
                    'created_at'=> '2024-12-06 05:20:55.000000',
                    'updated_at'=> '2024-12-06 05:20:55.000000',
                ],
                [
                    'id'=> '51',
                    'User_Id'=> '26',
                    'O_Name'=> 'Afiq Hamdan',
                    'O_Street_1'=> '13, Taman Dahlia, Taman Universiti',
                    'O_Postcode'=> '40000',
                    'O_City'=> 'Kajang',
                    'O_State'=> 'Selangor',
                    'O_Email'=> 'avi9@gmail.com',
                    'O_Phone'=> '018-3346769',
                    'O_Payment'=> 'Cash',
                 
                    'T_Pax'=> '3',
                    'O_Total_Price'=> '5.00',
                    'O_Type'=> 'dineIn',
                    'O_Status'=> '1',
                    'Tracking_No'=> rand(1000, 9999),
                    'Remarks'=> 'Call me',
                    'created_at'=> '2024-12-07 05:20:55.000000',
                    'updated_at'=> '2024-12-07 05:20:55.000000',
                ],
                [
                    'id'=> '52',
                    'User_Id'=> '1',
                    'O_Name'=> 'Nurul Lydia',
                    'O_Street_1'=> '13, Taman Dahlia, Taman Universiti',
                    'O_Postcode'=> '40000',
                    'O_City'=> 'Kajang',
                    'O_State'=> 'Selangor',
                    'O_Email'=> 'avi9@gmail.com',
                    'O_Phone'=> '018-3346769',
                    'O_Payment'=> 'Cash',
                 
                    'T_Pax'=> '3',
                    'O_Total_Price'=> '5.00',
                    'O_Type'=> 'dineIn',
                    'O_Status'=> '1',
                    'Tracking_No'=> rand(1000, 9999),
                    'Remarks'=> 'Call me',
                    'created_at'=> '2024-12-08 05:20:55.000000',
                    'updated_at'=> '2024-12-08 05:20:55.000000',
                ],
                [
                    'id'=> '53',
                    'User_Id'=> '6',
                    'O_Name'=> 'Muhammad Hafeez',
                    'O_Street_1'=> '13, Taman Dahlia, Taman Universiti',
                    'O_Postcode'=> '40000',
                    'O_City'=> 'Kajang',
                    'O_State'=> 'Selangor',
                    'O_Email'=> 'avi9@gmail.com',
                    'O_Phone'=> '018-3346769',
                    'O_Payment'=> 'Cash',
                 
                    'T_Pax'=> '3',
                    'O_Total_Price'=> '5.00',
                    'O_Type'=> 'dineIn',
                    'O_Status'=> '1',
                    'Tracking_No'=> rand(1000, 9999),
                    'Remarks'=> 'Call me',
                    'created_at'=> '2024-12-09 05:20:55.000000',
                    'updated_at'=> '2024-12-09 05:20:55.000000',
                ],
                [
                    'id'=> '54',
                    'User_Id'=> '7',
                    'O_Name'=> 'Navitha Pariva',
                    'O_Street_1'=> '13, Taman Dahlia, Taman Universiti',
                    'O_Postcode'=> '40000',
                    'O_City'=> 'Kajang',
                    'O_State'=> 'Selangor',
                    'O_Email'=> 'avi9@gmail.com',
                    'O_Phone'=> '018-3346769',
                    'O_Payment'=> 'Cash',
                 
                    'T_Pax'=> '3',
                    'O_Total_Price'=> '5.00',
                    'O_Type'=> 'dineIn',
                    'O_Status'=> '1',
                    'Tracking_No'=> rand(1000, 9999),
                    'Remarks'=> 'Call me',
                    'created_at'=> '2024-01-09 05:20:55.000000',
                    'updated_at'=> '2024-01-09 05:20:55.000000',
                ],
                [
                    'id'=> '55',
                    'User_Id'=> '13',
                    'O_Name'=> 'Dong Si Cheng',
                    'O_Street_1'=> '13, Taman Dahlia, Taman Universiti',
                    'O_Postcode'=> '40000',
                    'O_City'=> 'Kajang',
                    'O_State'=> 'Selangor',
                    'O_Email'=> 'avi9@gmail.com',
                    'O_Phone'=> '018-3346769',
                    'O_Payment'=> 'Cash',
                 
                    'T_Pax'=> '3',
                    'O_Total_Price'=> '5.00',
                    'O_Type'=> 'dineIn',
                    'O_Status'=> '1',
                    'Tracking_No'=> rand(1000, 9999),
                    'Remarks'=> 'Call me',
                    'created_at'=> '2024-01-10 05:20:55.000000',
                    'updated_at'=> '2024-01-10 05:20:55.000000',
                ]
        
            ]);
    }
}
