<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class UsersSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB:: table('users')->insert ([[
            // 'id' => '1',
            'Name' => 'Nurul Lydia',
            'Email' => 'lydia@gmail.com',
            'Password' => Hash::make('lydia12345'),
            'occupation' => 'Student',
            'gender' => 'Female',
            'birthdate' => '1997-09-18',
            'race'=> 'Malay',
            'marital' => 'Single',
            'Street_1' => 'No 313, Blok Salak',
            'Postcode' => '31350',
            'City' => 'Serdang',
            'State' => 'Selangor',
            'Phone' => '013-3879380',
            'created_at' => '2024-01-19 10:47:14'

        ],
        [
            // 'id' => '2',
            'Name' => 'Lim Chong Heng',
            'Email' => 'chonghg89@gmail.com',
            'Password' => Hash::make('chong12345'),
            'occupation' => 'Auditor',
            'gender' => 'Female',
            'birthdate' => '1989-10-18',
            'race'=> 'Chinese',
            'marital' => 'Married',
            'Street_1' => 'KM 3, Jalan Kebun',
            'Postcode' => '43650',
            'City' => 'Kajang',
            'State' => 'Selangor',
            'Phone' => '014-3456777',
            'created_at' => '2024-01-19 10:47:14'
        ],
        [
            // 'id' => '3',
            'Name' => 'Avinesh A/L Veloo',
            'Email' => 'avi9@gmail.com',
            'Password' => Hash::make('avi12345'),
            'occupation' => 'Student',
            'gender' => 'Male',
            'birthdate' => '1999-01-27',
            'race'=> 'Indian',
            'marital' => 'Single',
            'Street_1' => '13, Taman Dahlia, Taman Universiti',
            'Postcode' => '40000',
            'City' => 'Kajang',
            'State' => 'Selangor',
            'Phone' => '018-3346769',
            'created_at' => '2024-01-19 10:47:14'
        ],
        [
            // 'id' => '4',
            'Name' => 'Muhammad Adli',
            'Email' => 'adli@gmail.com',
            'Password' => Hash::make('adli12345'),
            'occupation' => 'Engineer',
            'gender' => 'Male',
            'birthdate' => '1993-01-27',
            'race'=> 'Malay',
            'marital' => 'Single',
            'Street_1' => '13, Taman Dahlia, Taman Universiti',
            'Postcode' => '40000',
            'City' => 'Kajang',
            'State' => 'Selangor',
            'Phone' => '018-3346769',
            'created_at' => '2024-01-29 10:47:14'
        ],
        [
            // 'id' => '5',
            'Name' => 'Muhammad Ashraf',
            'Email' => 'Ashraf@gmail.com',
            'Password' => Hash::make('Ashraf12345'),
            'occupation' => 'Engineer',
            'gender' => 'Male',
            'birthdate' => '1985-01-27',
            'race'=> 'Malay',
            'marital' => 'Widowed',
            'Street_1' => '13, Taman Dahlia, Taman Universiti',
            'Postcode' => '40000',
            'City' => 'Kajang',
            'State' => 'Selangor',
            'Phone' => '018-3346769',
            'created_at' => '2024-01-29 10:47:14'
        ],
        [
            // 'id' => '6',
            'Name' => 'Muhammad Hafeez',
            'Email' => 'Hafeez@gmail.com',
            'Password' => Hash::make('Hafeez12345'),
            'occupation' => 'Engineer',
            'gender' => 'Male',
            'birthdate' => '1985-01-27',
            'race'=> 'Other',
            'marital' => 'Divorced',
            'Street_1' => '13, Taman Dahlia, Taman Universiti',
            'Postcode' => '40000',
            'City' => 'Kajang',
            'State' => 'Selangor',
            'Phone' => '018-3346769',
            'created_at' => '2024-01-02 10:47:14'
        ],
        [
            // 'id' => '7',
            'Name' => 'Navitha Pariva',
            'Email' => 'Navitha@gmail.com',
            'Password' => Hash::make('Navitha12345'),
            'occupation' => 'Engineer',
            'gender' => 'Female',
            'birthdate' => '1993-01-27',
            'race'=> 'Indian',
            'marital' => 'Divorced',
            'Street_1' => '13, Taman Dahlia, Taman Universiti',
            'Postcode' => '40000',
            'City' => 'Kajang',
            'State' => 'Selangor',
            'Phone' => '018-3346769',
            'created_at' => '2024-01-02 10:47:14'
        ],
        [
            // 'id' => '8',
            'Name' => 'Pretty Sintha',
            'Email' => 'Pretty@gmail.com',
            'Password' => Hash::make('Navitha12345'),
            'occupation' => 'Engineer',
            'gender' => 'Female',
            'birthdate' => '1993-01-27',
            'race'=> 'Indian',
            'marital' => 'Divorced',
            'Street_1' => '13, Taman Dahlia, Taman Universiti',
            'Postcode' => '40000',
            'City' => 'Kajang',
            'State' => 'Selangor',
            'Phone' => '018-3346769',
            'created_at' => '2024-01-02 10:47:14'
        ],
        [
            // 'id' => '9',
            'Name' => 'Olivia Charles',
            'Email' => 'Olivia@gmail.com',
            'Password' => Hash::make('Olivia12345'),
            'occupation' => 'Engineer',
            'gender' => 'Female',
            'birthdate' => '1979-01-27',
            'race'=> 'Other',
            'marital' => 'Widowed',
            'Street_1' => '13, Taman Dahlia, Taman Universiti',
            'Postcode' => '40000',
            'City' => 'Kajang',
            'State' => 'Selangor',
            'Phone' => '018-3346769',
            'created_at' => '2024-01-02 10:47:14'
        ],
        [
            // 'id' => '10',
            'Name' => 'Emma Justin',
            'Email' => 'Emma@gmail.com',
            'Password' => Hash::make('Emma12345'),
            'occupation' => 'Engineer',
            'gender' => 'Chinese',
            'birthdate' => '1979-01-27',
            'race'=> 'Other',
            'marital' => 'Married',
            'Street_1' => '13, Taman Dahlia, Taman Universiti',
            'Postcode' => '40000',
            'City' => 'Kajang',
            'State' => 'Selangor',
            'Phone' => '018-3346769',
            'created_at' => '2024-10-21 10:47:14'
        ],
        [
            // 'id' => '11',
            'Name' => 'Chu Hua Charles',
            'Email' => 'Chu Hua@gmail.com',
            'Password' => Hash::make('Chu Hua12345'),
            'occupation' => 'Engineer',
            'gender' => 'Female',
            'birthdate' => '1979-01-27',
            'race'=> 'Chinese',
            'marital' => 'Married',
            'Street_1' => '13, Taman Dahlia, Taman Universiti',
            'Postcode' => '40000',
            'City' => 'Kajang',
            'State' => 'Selangor',
            'Phone' => '018-3346769',
            'created_at' => '2024-01-02 10:47:14'
        ],
         [
        //     'id' => '12',
            'Name' => 'Qian Sheng',
            'Email' => 'Qian@gmail.com',
            'Password' => Hash::make('Qian12345'),
            'occupation' => 'Engineer',
            'gender' => 'Female',
            'birthdate' => '1979-01-27',
            'race'=> 'Chinese',
            'marital' => 'Married',
            'Street_1' => '13, Taman Dahlia, Taman Universiti',
            'Postcode' => '40000',
            'City' => 'Kajang',
            'State' => 'Selangor',
            'Phone' => '018-3346769',
            'created_at' => '2024-01-02 10:47:14'
        ],
        [
            // 'id' => '13',
            'Name' => 'Dong Si Cheng',
            'Email' => 'Dong@gmail.com',
            'Password' => Hash::make('Dong12345'),
            'occupation' => 'Engineer',
            'gender' => 'Male',
            'birthdate' => '1999-01-27',
            'race'=> 'Chinese',
            'marital' => 'Single',
            'Street_1' => '13, Taman Dahlia, Taman Universiti',
            'Postcode' => '40000',
            'City' => 'Kajang',
            'State' => 'Selangor',
            'Phone' => '018-3346769',
            'created_at' => '2024-10-21 10:47:14'
        ],
        [
            // 'id' => '14',
            'Name' => 'Sean Leng',
            'Email' => 'Leng@gmail.com',
            'Password' => Hash::make('Leng12345'),
            'occupation' => 'Engineer',
            'gender' => 'Male',
            'birthdate' => '1999-01-27',
            'race'=> 'Chinese',
            'marital' => 'Single',
            'Street_1' => '13, Taman Dahlia, Taman Universiti',
            'Postcode' => '40000',
            'City' => 'Kajang',
            'State' => 'Selangor',
            'Phone' => '018-3346769',
            'created_at' => '2024-01-06 10:47:14'
        ],
        [
            // 'id' => '15',
            'Name' => 'Prasanth',
            'Email' => 'Prasanth@gmail.com',
            'Password' => Hash::make('Prasanth12345'),
            'occupation' => 'Engineer',
            'gender' => 'Male',
            'birthdate' => '1999-01-27',
            'race'=> 'Indian',
            'marital' => 'Single',
            'Street_1' => '13, Taman Dahlia, Taman Universiti',
            'Postcode' => '40000',
            'City' => 'Kajang',
            'State' => 'Selangor',
            'Phone' => '018-3346769',
            'created_at' => '2024-01-06 10:47:14'
        ],
        [
            // 'id' => '16',
            'Name' => 'Hakim',
            'Email' => 'Hakim@gmail.com',
            'Password' => Hash::make('Hakim12345'),
            'occupation' => 'Engineer',
            'gender' => 'Male',
            'birthdate' => '1984-01-27',
            'race'=> 'Malay',
            'marital' => 'Married',
            'Street_1' => '13, Taman Dahlia, Taman Universiti',
            'Postcode' => '40000',
            'City' => 'Kajang',
            'State' => 'Selangor',
            'Phone' => '018-3346769',
            'created_at' => '2024-01-28 10:47:14'
        ],
        [
            // 'id' => '17',
            'Name' => 'Christine',
            'Email' => 'Christine@gmail.com',
            'Password' => Hash::make('Christine12345'),
            'occupation' => 'Engineer',
            'gender' => 'Female',
            'birthdate' => '1984-01-27',
            'race'=> 'Chinese',
            'marital' => 'Married',
            'Street_1' => '13, Taman Dahlia, Taman Universiti',
            'Postcode' => '40000',
            'City' => 'Kajang',
            'State' => 'Selangor',
            'Phone' => '018-3346769',
            'created_at' => '2024-01-28 10:47:14'
        ],
        [
            // 'id' => '18',
            'Name' => 'Shenti',
            'Email' => 'Shenti@gmail.com',
            'Password' => Hash::make('Shenti12345'),
            'occupation' => 'Engineer',
            'gender' => 'Female',
            'birthdate' => '1984-01-27',
            'race'=> 'Chinese',
            'marital' => 'Married',
            'Street_1' => '13, Taman Dahlia, Taman Universiti',
            'Postcode' => '40000',
            'City' => 'Kajang',
            'State' => 'Selangor',
            'Phone' => '018-3346769',
            'created_at' => '2024-01-28 10:47:14'
        ],
        [
            // 'id' => '19',
            'Name' => 'Christine',
            'Email' => 'Christine@gmail.com',
            'Password' => Hash::make('Christine12345'),
            'occupation' => 'Engineer',
            'gender' => 'Female',
            'birthdate' => '1984-01-27',
            'race'=> 'Chinese',
            'marital' => 'Married',
            'Street_1' => '13, Taman Dahlia, Taman Universiti',
            'Postcode' => '40000',
            'City' => 'Kajang',
            'State' => 'Selangor',
            'Phone' => '018-3346769',
            'created_at' => '2024-01-28 10:47:14'
        ],
        [
            // 'id' => '20',
            'Name' => 'Shree Tanusha',
            'Email' => 'Shree@gmail.com',
            'Password' => Hash::make('Shree12345'),
            'occupation' => 'Engineer',
            'gender' => 'Female',
            'birthdate' => '1996-01-27',
            'race'=> 'Indian',
            'marital' => 'Married',
            'Street_1' => '13, Taman Dahlia, Taman Universiti',
            'Postcode' => '40000',
            'City' => 'Kajang',
            'State' => 'Selangor',
            'Phone' => '018-3346769',
            'created_at' => '2024-01-28 10:47:14'
        ],
        [
            // 'id' => '21',
            'Name' => 'Imran',
            'Email' => 'Imran@gmail.com',
            'Password' => Hash::make('Imran12345'),
            'occupation' => 'Engineer',
            'gender' => 'Male',
            'birthdate' => '1984-01-27',
            'race'=> 'Chinese',
            'marital' => 'Married',
            'Street_1' => '13, Taman Dahlia, Taman Universiti',
            'Postcode' => '40000',
            'City' => 'Kajang',
            'State' => 'Selangor',
            'Phone' => '018-3346769',
            'created_at' => '2024-10-06 10:47:14'
        ],
        [
            // 'id' => '22',
            'Name' => 'Abdul Razak',
            'Email' => 'Razak@gmail.com',
            'Password' => Hash::make('Razak12345'),
            'occupation' => 'Engineer',
            'gender' => 'Female',
            'birthdate' => '1996-01-27',
            'race'=> 'Malay',
            'marital' => 'Single',
            'Street_1' => '13, Taman Dahlia, Taman Universiti',
            'Postcode' => '40000',
            'City' => 'Kajang',
            'State' => 'Selangor',
            'Phone' => '018-3346769',
            'created_at' => '2024-06-10 10:47:14'
        ],
        [
            // 'id' => '23',
            'Name' => 'Ahmad Hazim',
            'Email' => 'Hazim@gmail.com',
            'Password' => Hash::make('Hazim12345'),
            'occupation' => 'Engineer',
            'gender' => 'Male',
            'birthdate' => '1981-01-27',
            'race'=> 'Malay',
            'marital' => 'Single',
            'Street_1' => '13, Taman Dahlia, Taman Universiti',
            'Postcode' => '40000',
            'City' => 'Kajang',
            'State' => 'Selangor',
            'Phone' => '018-3346769',
            'created_at' => '2024-06-10 10:47:14'
        ],
        [
            // 'id' => '24',
            'Name' => 'Iman Shakil',
            'Email' => 'Iman@gmail.com',
            'Password' => Hash::make('Iman12345'),
            'occupation' => 'Engineer',
            'gender' => 'Male',
            'birthdate' => '1997-01-27',
            'race'=> 'Malay',
            'marital' => 'Single',
            'Street_1' => '13, Taman Dahlia, Taman Universiti',
            'Postcode' => '40000',
            'City' => 'Kajang',
            'State' => 'Selangor',
            'Phone' => '018-3346769',
            'created_at' => '2024-06-10 10:47:14'
        ],
        [
            // 'id' => '25',
            'Name' => 'Shivaansh',
            'Email' => 'Shivaansh@gmail.com',
            'Password' => Hash::make('Shivaansh12345'),
            'occupation' => 'Engineer',
            'gender' => 'Male',
            'birthdate' => '1981-01-27',
            'race'=> 'Indian',
            'marital' => 'Divorced',
            'Street_1' => '13, Taman Dahlia, Taman Universiti',
            'Postcode' => '40000',
            'City' => 'Kajang',
            'State' => 'Selangor',
            'Phone' => '018-3346769',
            'created_at' => '2024-06-10 10:47:14'
        ],
        [
            // 'id' => '26',
            'Name' => 'Afiq Hamdan',
            'Email' => 'Afiq@gmail.com',
            'Password' => Hash::make('Afiq12345'),
            'occupation' => 'Engineer',
            'gender' => 'Male',
            'birthdate' => '1997-01-27',
            'race'=> 'Malay',
            'marital' => 'Single',
            'Street_1' => '13, Taman Dahlia, Taman Universiti',
            'Postcode' => '40000',
            'City' => 'Kajang',
            'State' => 'Selangor',
            'Phone' => '018-3346769',
            'created_at' => '2024-06-10 10:47:14'
        ],
        [
            // 'id' => '27',
            'Name' => 'Adib Hamdan',
            'Email' => 'Afiq@gmail.com',
            'Password' => Hash::make('Afiq12345'),
            'occupation' => 'Engineer',
            'gender' => 'Male',
            'birthdate' => '1997-01-27',
            'race'=> 'Malay',
            'marital' => 'Single',
            'Street_1' => '13, Taman Dahlia, Taman Universiti',
            'Postcode' => '40000',
            'City' => 'Kajang',
            'State' => 'Selangor',
            'Phone' => '018-3346769',
            'created_at' => '2024-06-10 10:47:14'
        ],
        [
            // 'id' => '28',
            'Name' => 'Haris Ibrahim',
            'Email' => 'Haris@gmail.com',
            'Password' => Hash::make('Haris12345'),
            'occupation' => 'Engineer',
            'gender' => 'Male',
            'birthdate' => '1997-01-27',
            'race'=> 'Malay',
            'marital' => 'Single',
            'Street_1' => '13, Taman Dahlia, Taman Universiti',
            'Postcode' => '40000',
            'City' => 'Kajang',
            'State' => 'Selangor',
            'Phone' => '018-3346769',
            'created_at' => '2024-06-10 10:47:14'
        ],
        [
            // 'id' => '29',
            'Name' => 'Adam Ismail',
            'Email' => 'Adam@gmail.com',
            'Password' => Hash::make('Adam12345'),
            'occupation' => 'Engineer',
            'gender' => 'Male',
            'birthdate' => '1996-01-27',
            'race'=> 'Malay',
            'marital' => 'Single',
            'Street_1' => '13, Taman Dahlia, Taman Universiti',
            'Postcode' => '40000',
            'City' => 'Kajang',
            'State' => 'Selangor',
            'Phone' => '018-3346769',
            'created_at' => '2024-06-10 10:47:14'
        ],
        [
            // 'id' => '30',
            'Name' => 'Ammar Idham',
            'Email' => 'Ammar@gmail.com',
            'Password' => Hash::make('Ammar12345'),
            'occupation' => 'Engineer',
            'gender' => 'Male',
            'birthdate' => '1985-01-27',
            'race'=> 'Malay',
            'marital' => 'Widowed',
            'Street_1' => '13, Taman Dahlia, Taman Universiti',
            'Postcode' => '40000',
            'City' => 'Kajang',
            'State' => 'Selangor',
            'Phone' => '018-3346769',
            'created_at' => '2024-01-29 10:47:14'
        ]
    ]);
    
    }
}